apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-service
  namespace: sre-lab
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: orders-service
  namespaceSelector:
    matchNames:
      - sre-lab
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
